### PR TITLE
fix duration for workload

### LINKED ISSUE #169: in deployment detail page, 持续时间字段计算有误
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- Karmada Dashboard version:
- Others:

Image

### PR DESCRIPTION
**Pull request by warjiang**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The duration of workload is hard coded in the frontend code, just fix that.
**Which issue(s) this PR fixes**:
Fixes #169 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- fix the duration calculation for workload 
```

### CODE REVIEW

File: ui/apps/dashboard/src/utils/time.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import dayjs from 'dayjs';
+
+export function calculateDuration(start: string | undefined) {
+  if (!start) return '-';
+  const startDate = dayjs(start);
+  const endDate = dayjs(); // 当前时间
```
Comment (samzong) [inline ui/apps/dashboard/src/utils/time.ts:6]: The backend usually returns the server time, which should be UTC by default, and it may be necessary to handle the time zone differences; here, is it the browser time being obtained?

File: ui/apps/dashboard/src/main.tsx [hunk 2]
```diff
@@ -1,57 +1,60 @@
...
+  })
+  .then(() => {
+    initRoute();
+    ReactDOM.createRoot(document.getElementById('root')!).render(
+      <React.StrictMode>
+        <App />
+      </React.StrictMode>,
+    );
+  })
+  .catch(() => {});
```
Comment (samzong) [inline ui/apps/dashboard/src/main.tsx:60]:
```suggestion
  .catch(() => {
      console.error('i18n initialization failed:', error);
  });
```

Add error alerts for `.catch` to facilitate subsequent debugging?

Comment (warjiang) [reply ui/apps/dashboard/src/main.tsx]: already print extra error msg

File: ui/apps/dashboard/src/utils/time.ts (hunk 1 above)
Comment (warjiang) [reply ui/apps/dashboard/src/utils/time.ts:6]: it's a good question 🤔 , and dayjs(which we used in our project) use browser timezone in default, and if the timezone differs from local(here refer our personal computer) and server(which means the karmada-dashboard-api ), the calculation of duration may be wrong

Comment (samzong) [reply ui/apps/dashboard/src/utils/time.ts:6]: dayjs support plugin utc and timezone.

Comment (warjiang) [reply ui/apps/dashboard/src/utils/time.ts:6]: > dayjs support plugin utc and timezone.

yeah, but that's not key problem, key problem is the difference between client time for different regions. In fact the duration for workload is an absolute number, should be different across regions.

**Comment by RainbowMango** [comment]
I think we can squash the commits before moving this forward.

File: ui/apps/dashboard/src/utils/time.ts (hunk 1 above)
Comment (samzong) [reply ui/apps/dashboard/src/utils/time.ts:6]: maybe just convert it to the current time zone of the browser.

No need to consider multiple time zones. like this.

```typescript
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import timezone from 'dayjs/plugin/timezone';

dayjs.extend(utc);
dayjs.extend(timezone);

export function calculateDuration(start: string | undefined) {
  if (!start) return '-';
  // Convert UTC server time to browser's local timezone
  const startDate = dayjs.utc(start).local();
  const endDate = dayjs();
  const duration = dayjs.duration(endDate.diff(startDate));
  return duration.humanize();
}
```

**Comment by warjiang** [comment]
@samzong plz check it again~

**Review by samzong — COMMENTED** [review]
great!
